name: production workflow

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      # Push to Github Container Registry
      - name: Push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: | 
            ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
          load: true
      - run: docker push ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}